@startuml Webinar Format Process

skinparam activity {
    BackgroundColor PowderBlue
    ArrowColor Navy
    ArrowFontColor MediumSlateBlue
    EndColor ForestGreen
}

(*) -->[Idea Proposed] Idea

Idea --> (*)

@enduml