@startuml Project Format Process

skinparam defaultFontName Ubuntu Light
skinparam backgroundColor transparent

skinparam activity {
    BackgroundColor PowderBlue
    StartColor ForestGreen
    EndColor ForestGreen
    FontStyle bold
}

skinparam arrow {
    Color SteelBlue
    FontColor SteelBlue
}

skinparam note {
    BackgroundColor AliceBlue
    FontSize 10
}

note right
    A topic arise
end note
(*) -->[Submission] Draft
note left
    An Idea (issue) is created
end note
-->[Clarification] Ready
note right
    The idea, the main goal,
    the expected result, and the
    required effort is clarified
end note
-->[Advertisement] Sourced
note right
    The contributors are
    identified and the kick-off
    is planned for a milestone
end note
..>[Milestone starts] In progress
note left
    The presentation and additional
    artifacts (code) is created by
    the trainer, and reviewed by
    at least one of the staff members
end note
--> TBD
note right
    An event is created on the
    WeAreCommunity page and
    registration is enabled
end note
..>[The webinar\n**date**\narrives] Conducted
note left
    The webinar is conducted at
    the given date/time, all the
    questions answered or followed
    up, the recording and slides
    are available
end note
if "Summary article is needed?" then
    -right->[Yes] In summary
    note right
        An article is created on the
        WeAreCommunity page,
        summarizing the webinar.
    end note
    -->[Administration] Done
else
    -->[No, Administration] Done
endif
note left
    The recording is uploaded to
    VideoPortal and the talk,
    alongside with the slides and
    link to the source code
    (if created)
end note
..> (*)
note right
    We collect statistics and
    feedback about the webinar:
    views, questions, speaker badge, etc
end note

@enduml