name: Add Task List to Issues
on:
  # workflow_dispatch
  issues:
    types:
     - opened
     - labeled
jobs:
  add-task-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add Task List to Issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./tasks/scripts/add-task.js')
            await script({github, context})
          
